# Generated by Django 5.2.6 on 2025-09-30 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='district',
            field=models.CharField(default='KTT', max_length=100),
        ),
    ]
