# Generated by Django 5.2.6 on 2025-10-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='professional',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='listing',
            name='district',
            field=models.CharField(max_length=100),
        ),
    ]
