# Generated by Django 5.2.6 on 2025-10-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_professional_alter_listing_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='professional',
            field=models.IntegerField(),
        ),
    ]
