# Generated by Django 5.2.6 on 2025-10-10 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_subject_remove_listing_screens_listing_room_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='professionals',
        ),
        migrations.AddField(
            model_name='listing',
            name='professionals',
            field=models.ManyToManyField(blank=True, to='listings.subject'),
        ),
    ]
